title: chartjs-theme-jekyll
email: chartjs-theme-jekyll@bartvaneynde.be
description: >- # this means to ignore newlines until "baseurl:"
  I could use a simple ChartsJS dashboard...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site, e.g. http://example.com


# search: true
permalink: /:categories/:year/:title/

# author: Bart Van Eynde
# logo: /assets/images/BartVanEynde_400x400.jpg


# Build settings
### theme: minima
### theme: jekyll-theme-basically-basic

# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
#   - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
  - docker_serve.sh
  - .gitignore
  - CHANGELOG.md
  - README.md
  - LICENSE
